/*QUICK MAPS REFERENCE GUIDE
MAPS:
0:  Starting from the bottom  startingFromTheBottom(stats& you)
1:  Outside your house        outside(stats& you)
2:  Kush Garden				 garden(stats& you)
3:  Road						 road(stats& you)
4:  Outskirts				 outskirts(stats& you)
5:  Evergreen City			 evergreenCity(stats& you)
6:  David's Store			 davidStore(stats& you)
7:  The Club					 daClub(stats& you)
8:		Hallway in da club	 hallway(stats& you)
9:      Bee's Office		 beeOffice(stats& you) --INITIALIZED
10: EV Downtown				 EVdowntown(stats& you)
11: Chief Keef's House		 chiefKeef(stats& you)
12: Jackie's Restaurant		 jackieRestaurant(stats& you)
13: EV City Hall			 cityHall(stats& you)
14: EV Mayor's Office		 mayorOffice(stats& you)
15: 101						 HWY101(stats& you)    -- UP TO HERE PUT IN loadmap()
16: In the chair @ Bee's	 inTheChair(stats& you)
17: Kenzo's					 kenzos(stats& you)
18: North Weedmont			 northWeedmont(stats& you)
19: Jason's Church			 jasonChurch(stats& you)
20: Caruana Factory			 caruana(stats& you)
21: Julian's Goat Farm       goatFarm(stats& you)
22: South Weedmont			 southWeedmont(stats& you)
23: The Manor				 manor(stats& you)
24: The Swamp				 swamp(stats& you)
25: Rotten Robbie			 rittenRibbie(stats& you)
26: San Fransisco Hub		 sfSquare(stats& you)
27: Outside Alcatraz		 outsideAlcatraz(stats& you)
28: Alcatraz Hub			 insideAlcatraz(stats& you)
29: Supply Closet			 supplyCloset(stats& you)
30: Your Cell				 yourCell(stats& you)
31: dankOneCell				 dankOneCell(stats& you)
32: Alcatraz Yard			 prisonYard(stats& you)
33: Fight Club				 fightClub(stats& you)
34: San Fransisco Downtown   sfDowntown(stats& you)
35: SFSU					 sfsu(stats& you)
36: SFSU Dorms				 dorms(stats& you)

*/